version: 2
sources:
- name: fellowship_24_25_data
  schema: fellowship_24_25
  tables:
  - name: Raw_Data_Baseline
    identifier: Raw_Data_sample
    description: This is a placeholder table & will be replaced with original. This
      table contains data of the baseline assessment for AY 24-25, for students in
      all classrooms. This table contains combined data for RF,RC & Math. This table
      comes from the master G-Sheet 'Baseline 2024_Overall Analysis'
    columns:
    - name: RF_
      description: Reading fluency score
    - name: City
      description: City where the student is located
    - name: Blends
      description: Assessment score for blends
    - name: Cohort
      description: Cohort identifier
    - name: Factual
      description: Score for factual questions
    - name: Grammar
      description: Score for grammar assessment
    - name: PM_Name
      description: Program manager's name
    - name: Advanced
      description: Advanced level score
    - name: Beginner
      description: Beginner level score
    - name: CVC_words
      description: Score for CVC words
    - name: Inference
      description: Score for inference questions
    - name: Passage_1
      description: Score for first passage
    - name: Passage_2
      description: Score for second passage
    - name: Developing
      description: Developing level score
    - name: Student_ID
      description: Unique identifier for each student
    - name: Vocabulary
      description: Score for vocabulary assessment
    - name: Fellow_Name
      description: Name of the fellow
    - name: School_Name
      description: Name of the school
    - name: Classroom_ID
      description: Identifier for the classroom
    - name: Grade_Taught
      description: Grade level taught
    - name: ID_Generator
      description: Generated ID for internal use
    - name: Intermediate
      description: Intermediate level score
    - name: Student_Name
      description: Name of the student
    - name: Letter_sounds
      description: Score for letter sounds
    - name: Magic_E_words
      description: Score for magic E words
    - name: RC_Assessed___
      description: Reading comprehension assessed score
    - name: Vowel_diagraphs
      description: Score for vowel diagraphs
    - name: Baseline_RF_Code
      description: Baseline reading fluency code
    - name: Baseline_RC_Level
      description: Baseline reading comprehension level
    - name: Critical_Thinking
      description: Score for critical thinking
    - name: Baseline_RC_Status
      description: Baseline reading comprehension status
    - name: Baseline_RF_Status
      description: Baseline reading fluency status
    - name: Consonant_diagraph
      description: Score for consonant diagraphs
    - name: Baseline_Math_Level
      description: Baseline math level
    - name: Basel_RC_Grade_Level
      description: Baseline reading comprehension grade level
    - name: Baseline_Math_Status
      description: Baseline math status
    - name: Baseline_Math_Mastery
      description: Baseline math mastery level
    - name: Multi_syllabelle_words
      description: Score for multi-syllable words
    - name: Baseline_Math___in_Time
      description: Baseline math score in time
    - name: Baseline_Math___in_Numbers
      description: Baseline math score in numbers
    - name: Baseline_Math___in_Geometry
      description: Baseline math score in geometry
    - name: Baseline_Math___in_Patterns
      description: Baseline math score in patterns
    - name: Baseline_Math___in_Operations
      description: Baseline math score in operations
    - name: Baseline_Math___in_Mensuration
      description: Baseline math score in mensuration
    - name: Baseline_Math___in_Data_Handling
      description: Baseline math score in data handling
    - name: _airbyte_raw_id
      description: Airbyte raw ID
    - name: _airbyte_extracted_at
      description: Timestamp when data was extracted by Airbyte
    - name: _airbyte_meta
      description: Metadata from Airbyte
  - name: Raw_Data_Midline
    identifier: Raw_Data_Midline
    description: This table contains data of the midline assessment for AY 24-25,
      for students in all classrooms. This table contains combined data for RF,RC
      & Math. This table comes from the master G-Sheet 'Midline 2024_Overall Analysis'
    columns:
    - name: RF_
      description: Reading fluency score
    - name: City
      description: City where the assessment took place
    - name: Blends
      description: Score for blends assessment
    - name: Cohort
      description: Cohort of students
    - name: Factual
      description: Score for factual comprehension
    - name: Grammar
      description: Score for grammar assessment
    - name: PM_Name
      description: Name of the project manager
    - name: Advanced
      description: Advanced level score
    - name: Beginner
      description: Beginner level score
    - name: CVC_words
      description: Score for CVC words assessment
    - name: Inference
      description: Score for inference assessment
    - name: Passage_1
      description: Score for passage 1 comprehension
    - name: Passage_2
      description: Score for passage 2 comprehension
    - name: Developing
      description: Developing level score
    - name: Student_ID
      description: Unique identifier for each student
    - name: Vocabulary
      description: Score for vocabulary assessment
    - name: Fellow_Name
      description: Name of the fellow conducting the assessment
    - name: School_Name
      description: Name of the school
    - name: Classroom_ID
      description: Unique identifier for each classroom
    - name: Grade_Taught
      description: Grade level taught
    - name: Intermediate
      description: Intermediate level score
    - name: Student_Name
      description: Name of the student
    - name: Letter_sounds
      description: Score for letter sounds assessment
    - name: Magic_E_words
      description: Score for magic E words assessment
    - name: RC_Assessed___
      description: Reading comprehension assessed score
    - name: Midline_RF_Code
      description: Code for midline reading fluency
    - name: Vowel_diagraphs
      description: Score for vowel diagraphs assessment
    - name: Midline_RC_Level
      description: Level for midline reading comprehension
    - name: Critical_Thinking
      description: Score for critical thinking assessment
    - name: Midline_RC_Status
      description: Status for midline reading comprehension
    - name: Midline_RF_Status
      description: Status for midline reading fluency
    - name: Consonant_diagraph
      description: Score for consonant diagraph assessment
    - name: Midline_Math_Level
      description: Level for midline math assessment
    - name: Midline_Math_Status
      description: Status for midline math assessment
    - name: Midline_Math_Mastery
      description: Mastery level for midline math
    - name: Midline_Math___in_Time
      description: Score for math in time assessment
    - name: Midline_RC_Grade_Level
      description: Grade level for midline reading comprehension
    - name: Multi_syllabelle_words
      description: Score for multi-syllable words assessment
    - name: Midline_Math___in_Numbers
      description: Score for math in numbers assessment
    - name: Midline_Math___in_Geometry
      description: Score for math in geometry assessment
    - name: Midline_Math___in_Patterns
      description: Score for math in patterns assessment
    - name: Midline_Math___in_Operations
      description: Score for math in operations assessment
    - name: Midline_Math___in_Mensuration
      description: Score for math in mensuration assessment
    - name: Midline_Math___in_Data_Handling
      description: Score for math in data handling assessment
    - name: _airbyte_raw_id
      description: Airbyte raw identifier
    - name: _airbyte_extracted_at
      description: Timestamp when data was extracted by Airbyte
    - name: _airbyte_meta
      description: Metadata from Airbyte
  - name: Raw_Data_Endline
    identifier: Raw_Data_Endline
    description: This table contains data of the endline assessment for AY 24-25,
      for students in all classrooms. This table contains combined data for RF,RC
      & Math. This table comes from the master G-Sheet 'Endline 2025_Overall data'
    columns:
    - name: RF_
      description: Reading fluency score
    - name: City
      description: City where the assessment took place
    - name: Blends
      description: Assessment score for blends
    - name: Cohort
      description: Cohort of the student
    - name: Factual
      description: Score for factual questions
    - name: Grammar
      description: Grammar assessment score
    - name: PM_Name
      description: Program Manager's name
    - name: Advanced
      description: Score for advanced level
    - name: Beginner
      description: Score for beginner level
    - name: CVC_words
      description: Score for CVC words
    - name: Inference
      description: Score for inference questions
    - name: Passage_1
      description: Score for comprehension of passage 1
    - name: Passage_2
      description: Score for comprehension of passage 2
    - name: Developing
      description: Score for developing level
    - name: Student_ID
      description: Unique identifier for each student
    - name: Vocabulary
      description: Vocabulary assessment score
    - name: Fellow_Name
      description: Name of the fellow conducting the assessment
    - name: School_Name
      description: Name of the school
    - name: Classroom_ID
      description: Identifier for the classroom
    - name: Grade_Taught
      description: Grade level taught in the classroom
    - name: Intermediate
      description: Score for intermediate level
    - name: Student_Name
      description: Name of the student
    - name: Letter_sounds
      description: Score for letter sounds
    - name: Magic_E_words
      description: Score for magic E words
    - name: RC_Assessed___
      description: Reading comprehension assessed score
    - name: Endline_RF_Code
      description: Endline reading fluency code
    - name: Vowel_diagraphs
      description: Score for vowel digraphs
    - name: Endline_RC_Level
      description: Endline reading comprehension level
    - name: Critical_Thinking
      description: Score for critical thinking
    - name: Endline_RC_Status
      description: Status of endline reading comprehension
    - name: Endline_RF_Status
      description: Status of endline reading fluency
    - name: Consonant_diagraph
      description: Score for consonant digraphs
    - name: Endline_Math_Level
      description: Endline math level
    - name: Endline_Math_Status
      description: Status of endline math assessment
    - name: Endline_Math_Mastery
      description: Math mastery level at endline
    - name: Endline_Math___in_Time
      description: Score for math in time
    - name: Endline_RC_Grade_Level
      description: Grade level for endline reading comprehension
    - name: Multi_syllabelle_words
      description: Score for multi-syllable words
    - name: Endline_Math___in_Numbers
      description: Score for math in numbers
    - name: Endline_Math___in_Geometry
      description: Score for math in geometry
    - name: Endline_Math___in_Patterns
      description: Score for math in patterns
    - name: Endline_Math___in_Operations
      description: Score for math in operations
    - name: Endline_Math___in_Mensuration
      description: Score for math in mensuration
    - name: Endline_Math___in_Data_Handling
      description: Score for math in data handling
    - name: _airbyte_raw_id
      description: Airbyte raw ID
    - name: _airbyte_extracted_at
      description: Timestamp when data was extracted
    - name: _airbyte_meta
      description: Metadata from Airbyte
